alibaba/weex

circle.yml
css/site.css
css/site.sass
demo.html
download.html
html/demo.html
html/index.html
html/nav_bar.tpl
index.html
index_m.html
js/index.js

Merge the branch , site go Open Source

* [site] make site open source ready

---

android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/core/WXSwipeLayout.java

* [android] remove refresh timeout

* [android] remove refresh timeout

---

examples/component/list/list-basic.we
examples/component/list/list-demo.we
examples/component/scroller-demo.we
examples/index.we

* [ios] add list-basic height

---

package.json

[all] weex-components version updated

---

examples/module/stream-demo.we

add post progresscallback for stream.we

* [example] add post progresscallback for stream.we

---

doc/advanced/integrate-to-android.md

* [android] add android app build doc

---

doc/components/scroller.md

* [doc] update scroller attribute

---

android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java

Add timer module to support functional timer feature

* [Android] Add timer support

---

html5/default/vm/compiler.js

example:
```vue
<template>
<div onclick="update">
<text repeat="list">{{$index+1}} - {{time}}</text>
<text>----</text>
<text repeat="list" track-by="time">{{$index+1}} - {{time}}</text>
<text>----</text>
<text repeat="(k,v) in list">{{k+1}} - {{v.time}}</text>
<text>----</text>
<text repeat="(k,v) in list" track-by="time">{{k+1}} - {{v.time}}</text>
</div>
</template>
<script>
module.exports = {
data: {
list: []
},
methods: {
update: function (e) {
this.list.push({ time: Date.now() })
}
}
}
</script>
```

[jsfm] fixed repeat binding

---

examples/README.md

* [doc] corrects a typo in examples/README.md

---

android/commons/src/main/java/com/alibaba/weex/commons/AbstractWeexActivity.java
android/inspector/build.gradle
android/inspector/debug.json
android/inspector/src/main/java/com/taobao/weex/devtools/debug/DebugBridge.java
android/inspector/src/main/java/com/taobao/weex/devtools/debug/DebugServerProxy.java
android/inspector/src/main/java/com/taobao/weex/devtools/inspector/protocol/module/WxDebug.java
android/playground/app/src/main/java/com/alibaba/weex/IndexActivity.java
android/playground/app/src/main/java/com/alibaba/weex/WXApplication.java
android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java
android/playground/app/src/main/java_zxing/com/google/zxing/client/android/CaptureActivity.java
android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXModuleManager.java
android/sdk/src/main/java/com/taobao/weex/common/IWXDebugProxy.java
android/sdk/src/main/java/com/taobao/weex/ui/WXComponentRegistry.java
android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/circlebar/CircleProgressBar.java
android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/circlebar/MaterialProgressDrawable.java

[android] update add reload framework 6a2b1b9
[android] add a stop method to IWXDebugProxy 5789700
[android] refresh the instance when reload called by the debug server fd2be06
[android] rename a var and update inspector buildtoolversion 7d1a1d5

scan QR code launch devtools

---

html5/browser/api/timer.js

h5render version of implementation to https://github.com/alibaba/weex/issues/627

html5 add clearTimeout & set/clear interval

---

CONTRIBUTING.md

* [doc] new branch policy

---

android/inspector/README.md
doc/tools/devtools.md

* [android] update the doc of devtools

---

doc/how-to/customize-a-native-component.md
doc/how-to/cuszomize-native-apis.md
doc/how-to/preview-in-browser.md
doc/tutorial.md

improve doc

---

examples/component/text-demo.we

* [example] add text line height example

---

doc/components/text.md

Doc feature  update text style

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
ios/sdk/WeexSDK/Sources/Debug/WXDebugTool.m
ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

* [iOS]  feature fix stat

---

doc/references/common-event.md

There are some changes in common event, which refer to lifecycle of page, please merge these changes to doc branch.

Doc feature lifecycle

---

doc/tutorial_source/tech_list_2.we

根据原来的tech_list_2.we的代码生成的效果是这样的
修改后的效果如下

[doc] fix example

---

doc/references/gesture.md

* [doc] Add constrain for gesture document.

* [doc] Add constrain for gesture document.

---

html5/browser/components/input.js

fix: make input's attributes updatable (like `value` etc.).

html5 fix input attributes

---

doc/faq.md
doc/references/cheatsheet.md

+ [doc] added a cheatsheet for frontend developers
+ [doc] added es version and frontend deps management in faq

[doc] added a cheatsheet

---

android/sdk/src/main/java/com/taobao/weex/adapter/DefaultWXHttpAdapter.java
android/sdk/src/main/java/com/taobao/weex/common/WXRequest.java
android/sdk/src/main/java/com/taobao/weex/http/Options.java
android/sdk/src/main/java/com/taobao/weex/http/WXStreamModule.java
examples/module/stream-demo.we
html5/browser/api/stream.js

0. add timeout option to fetch options
0. add PUT/DELETE/HEAD/PATCH method support
@luics

* [android] add timeout config and put/delete/head/patch method to fetch

---

android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
android/sdk/src/main/java/com/taobao/weex/ui/WXRenderManager.java
android/sdk/src/main/java/com/taobao/weex/ui/WXRenderStatement.java
android/sdk/src/test/java/com/taobao/weex/ui/WXRenderStatementTest.java

[android] Remove useless parameter 'instanceId' for RenderStatement

---

examples/component/list/list-basic.we

* the list need a height style, or a `flex:1;` to calculate the scroll view's height, otherwise it won't work.

example add height to list

---

android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java

fix android typo

---

doc/specs/js-framework-apis.md
doc/specs/virtual-dom-apis.md

Doc typo fix

---

android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java

Android refactor code

---

ios/sdk/WeexSDK/Sources/Handler/WXNavigationDefaultImpl.m

there are some changes in ios branch , please merge to dev branch.

* [ios] fix bug when url has chinese character.

---

doc/specs/js-bundle-format.md
doc/specs/js-framework-apis.md
doc/specs/virtual-dom-apis.md

1. added third-party JS Framework registration
2. updated virtual-DOM APIs description
* separated: (public) members, internal members, read-only members
* details supplement

Doc feature frameworks

---

doc/components/image.md

fix resize to attribute scope in image

* [doc] fix resize to attribute scope in image

---

doc/references/events/appear.md
doc/references/events/blur.md
doc/references/events/change.md
doc/references/events/click.md
doc/references/events/disappear.md
doc/references/events/focus.md
doc/references/events/input.md

* `click`
* `appear`
* `disappear`
* `focus`
* `blur`
* `change`
* `input`

[doc] added events documentations

---

README.md

* android runtime
* weex article 
* weex.help
* gitter.im

update repo README

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Module/WXStorageModule.h
ios/sdk/WeexSDK/Sources/Module/WXStorageModule.m
ios/sdk/WeexSDKTests/WXStorageTests.m

1. 重写 WXStorageModule.
1.1. 实现原理：存储结构分为三层，Memory->NSCache->File. 数据的大小决定其存储的位置；小于 1 KB的数据统一存储于 wxstage.json，大于 1 KB的数据存储于 hash(key) 为文件名的无后缀文件。
1.2 实现接口：
```
- (void)getAllKeys:(WXModuleCallback)callback;
- (void)setItem:(NSString *)key value:(NSString *)value callback:(WXModuleCallback)callback;
- (void)getItem:(NSString *)key callback:(WXModuleCallback)callback;
- (void)removeItem:(NSString *)key callback:(WXModuleCallback)callback;
```
2. 添加测试用例到 WeexSDK.

Ios feature localstorage

---

ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m

WXStorageModule 注册到 WXSDKEngine

register WXStorageModule on the WXSDKEngine

---

examples/module/stream-demo.we
ios/playground/Podfile
ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m

fix stream fetch response type
add status text for response

* [ios] fix stream fetch response type

---

ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.h
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m

* [ios] fix type of callback params

---

html5/default/core/state.js
html5/shared/index.js

* bring `Object.assign` polyfill back
* fixed methods context problem for repeat vms

[jsfm] bugfix

---

ios/WXDevtool/TBWXDevTool.xcodeproj/project.pbxproj
ios/WXDevtool/WXDevTool/Source/PonyDebugger/PDDebugger.h
ios/WXDevtool/WXDevTool/Source/PonyDebugger/PDDebugger.m
ios/WXDevtool/WXDevTool/Source/PonyDebugger/WXDevToolType.h
ios/WXDevtool/WXDevTool/Source/PonyDebugger/WXDevToolType.m
ios/WXDevtool/WXDevTool/Source/WXHeader/WXDevTool.m
ios/sdk/WeexSDK/Sources/Utility/WXLog.h

Ios feature devtools

---

ios/sdk/WeexSDK/Sources/Module/WXModalUIModule.m

iOS feature modal bugfix
number compatible

iOS feature modal bugfix

---

doc/SUMMARY.md
doc/modules/storage.md
examples/index.we
examples/module/storage-demo.we
html5/browser/api/index.js
html5/browser/api/storage.js

api definition:
```
setItem: function(key,value,callbackId)
getItem: function(key,callbackId)
removeItem: function(key,callbackId)
length: function(callbackId)
getAllKeys: function(callbackId)
```
usage is simple:
```
var storage = require('@weex-module/storage');
var me = this;
//setItem
storage.setItem('foo','foo-value');
//getItem
storage.getItem('foo',function(e){
console.log('get foo result:'+JSON.stringify(e));
me.getItemResult = 'get foo,value is '+e.data+'\n';
});
...
```

implement html5 storage

---

doc/modules/stream.md

* [doc] fix fetch doc

---

doc/syntax/data-binding.md

* [doc] Optimize change name example

---

ios/playground/WeexDemo.xcodeproj/project.pbxproj
ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Module/WXStorageModule.m
ios/sdk/WeexSDK/Sources/Utility/WXThreadSafeMutableDictionary.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility+Hash.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility+Hash.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

修复 length 返回错误的问题

---

html5/default/vm/compiler.js

1. use `util.isObject` instead of `typeof` to do the type check.
2. let the else statement match the `isObject` condition, not only
`oldStyle`.

* [jsfm] fix the $index bug described in #846

---

doc/syntax/display-logic.md

Added a notes in display logic document for issue #922 .

* [doc] add notes in display logic doc #922

---

android/sdk/src/main/java/com/taobao/weex/utils/WXResourceUtils.java
android/sdk/src/test/java/com/taobao/weex/utils/WXResourceUtilsTest.java

1. 采用正则表达式匹配字符串 2. colorMap改用直接存储color的int值 3.减少字符串的使用，改用直接进行数字计算 4.匹配某种规则但在处理数字时遇到不符合预期值，直接抛出error。如rgb(256,256,256), 由于中间256数字超出0~255，直接抛出error 5. 增加了单元测试WXResourceUtilsTest

* [android] optimize WXResourceUtils class

---

doc/modules/storage.md

+ [android] add storage doc

---

doc/components/text.md
doc/components/wxc-navpage.md
doc/syntax/display-logic.md
doc/syntax/main.md

* [doc] fix #101

---

doc/advanced/integrate-to-ios.md

* [doc] fix render code location

---

doc/modules/timer.md

+ [doc] Add doc for timer module.

+ [doc] Add doc for timer module.

---

examples/component/list/list-demo.we

* [ios] fix list-advanced demo crashed

* [ios] fix list-advanced demo

---

doc/modules/timer.md

* [Android] Fix timer API description.

* [Android] Fix timer API description.

---

README.md

Guide user using our toolkit who want to start a project without knowing what exactly Weex implemented.

[readme] added weex-toolkit tips

---

examples/module/storage-demo.we
examples/module/stream-demo.we
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

1. fix storage module in swift
2. fix stream example

* [ios] fix storage module in swift

---

doc/references/common-style.md

* [doc] update border doc

---

examples/vanilla/index.js
html5/runtime/framework-vanilla.js
html5/vanilla/index.js

Almost no capsulation at all. Just a vanilla JavaScript environment.

[jsfm] add vanilla framework

---

html5/runtime/framework-rx.js
package.json

[jsfm] add rx framework

---

doc/components/list.md
doc/components/scroller.md

+ [doc] Add restrictions about nested scroller/list.

+ [doc] Add restrictions about nested scroller/list

---

dist/weex-js-framework/package.json
html5/default/app/ctrl/misc.js
html5/default/util/index.js
html5/shared/promise.js
package.json

**v0.15.3**
* Promise polyfill in iOS 7/8
* memory leak bug
**v0.15.4**
* ES6 Set native polyfill in iOS
**v0.15.5**
* fixed bug for Set in v0.15.4

[jsfm] v0.15.5

---

doc/components/input.md

* [doc] support maxlength attributes for input component

* [doc] support maxlength for input component

---

doc/advanced/extend-to-html5.md

update adding extensions to weex html5

doc update extending weex html5

---

html5/browser/extend/api/stream.js

fix jsonp callback's response format for `stream.fetch`.

html5 fix jsonp callback error

---

ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m

fix input disabled attribute bug

* [ios] fix input disabled attribute bug

---

.gitignore
circle.yml
css/showcase.css
demo.html

1. Showcase adapter into mobile phones and pad version.
2. use media css query.
3. delete some js libs.

* [website] Showcase adapter into mobile phones and pad version

---

doc/advanced/extend-to-html5.md

replace the url with new one using the -web suffix.

doc add platform to url

---

doc/tools/devtools-android.md

* [doc] update the android devtools readme

---

html5/default/static/life.js

Fix the memory leak problem.
@cxfeng1 @fkysly

+ [jsfm] Clear registered common modules while destroy app instance

---

android/sdk/src/main/java/com/taobao/weex/ui/view/WXScrollView.java

* [android] fix #1102

---

demo.html

add cnzz script to showcase page .
@lvscar  is it right?

* [website] add cnzz script to showcase page

---

doc/modules/animation.md

remove animation config of `transform-origin`. It should be  a style setting.

doc fix transform-origin demo

---

examples/component/list/list-demo.we
examples/component/scroller-demo.we

fix scroller-demo with `append="node"` and add overflow setting to list-demo

example bugfix scroller

---

doc/modules/animation.md

* [Android] Fix syntax error, which will cause JS Transformer error.

* [Android] Fix syntax error, which will cause JS Transformer error.

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Component/WXCanvasComponent.h
ios/sdk/WeexSDK/Sources/Component/WXCanvasComponent.m
ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
ios/sdk/WeexSDK/Sources/Module/WXCanvasModule.h
ios/sdk/WeexSDK/Sources/Module/WXCanvasModule.m

Add Canvas Componet

---

html5/shared/promise.js

Fix the potential memory leak in iOS.

* [jsfm] always use Promise polyfill in iOS

---

ios/sdk/WeexSDK/Sources/Component/WXCanvasComponent.m

canvas component property error fix

canvas component property error fix

---

html5/default/vm/directive.js

* [jsfm] fix merge classStyle fail between nested components

---

html5/default/app/ctrl/misc.js

Disable the batched `callNative` for better render performance.
@Tancy

* [jsfm] disable the batched callNative behavior

---

html5/browser/base/droot.js
html5/browser/base/root.js
html5/browser/index.js

downgrade scrollable components like `scroller`/`list` supports `loadmore` events.

html5 downgrade root support loadmore

---

css/download.css
css/site.css
download.html

1. download page adapter into mobile phones and pad version.
2. delete sourceMappingURL (css/site.css).
3. add css/download.css file.

* [website] download page adapter into mobile phones and pad version.

---

doc/syntax/display-logic.md
doc/syntax/main.md
doc/syntax/render-logic.md

There are three spelling mistakes in the syntax chapter of doc.

Update docs(spelling mistakes)

---

doc/components/cell.md
doc/components/list.md

*[doc] add translation

---

package.json

fix toast of modals, which doesn't disappear after toasting for a duration.

html5 fix toast for modals

---

doc/how-to/customize-a-native-component.md
doc/how-to/debug-with-html5.md

There are some spelling mistakes in chapter "**How-tos**"

Update chapter "How-tos" in doc(spelling mistake)

---

html5/browser/base/component/sticky.js

html5 fix sticky top

---

html5/test/unit/default/test.js

update long signals control case timeout 500000

* [jsfm] update long signals control case timeout 500000

---

doc/components/text.md
doc/faq.md

* [doc] add faq for text line-height

---

html5/browser/extend/components/spinner/index.js
html5/browser/extend/components/spinner/spinner.css

fix bug of null rules of stylesheet in spinner.

html5 fix bug of spinner

---

android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXSliderNeighbor.java
android/sdk/src/main/java/com/taobao/weex/ui/view/WXCircleViewPager.java
examples/component/slider-neighbor/silder-neighbor.we
examples/component/slider-neighbor/slider-neighbor-item.we
examples/component/slider-neighbor/slider-neighbor-page.we
examples/index.we

增强了Silder，同时显示左右元素各一点点的效果。
因为改的比较多，并且AutoPlay属性的关系，所以是拓展了一个子类。
Known Issus:
1. AutoPlay参数不好用，因为PageTransformer.transformPage()有时不会回调到。导致动画逻辑没更新上去。
2. wxc-panel 左边有个默认是margin, 会导致左右两个view，漏出来的大小不一致。

Android feature slider enhancement

---

html5/browser/extend/components/tabheader/index.js

html5 fix registration of tabheader

---

doc/modules/navigator.md
doc/modules/storage.md

re-commit #1198 & #1199 for lack of CLA commits

[doc] added some cn links

---

doc/tools/devtools.md

* [doc] update the doc of devtools

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXSliderNeighbor.java
android/sdk/src/main/java/com/taobao/weex/ui/view/WXCirclePageAdapter.java

1. 两侧的item点击进入对应的detail
2.  都有对应的scale值，default值，中间item为0.9，左右item为0.8
3. 中间item位置固定，左右item距中间item的间隙固定，数值暂定为25；
4. neighbor-space属性取消

slider neighbor update

---

android/sdk/src/main/java/com/taobao/weex/http/WXStreamModule.java

* [android] issue #1239

---

doc/components/slider.md

add doc: slider Attributes `index`

---

.wwprc
html5/browser/extend/api/geolocation.js

add geolocation module, which has 3 valid API:
* getCurrentPosition
* watchPosition
* clearWatch

html5 add geolocation module

---

ios/sdk/WeexSDK/Sources/Module/WXStorageModule.h
ios/sdk/WeexSDK/Sources/Module/WXStorageModule.m
ios/sdk/WeexSDKTests/WXStorageTests.m

1. Add Total storage limit to 5M. No limit in original version.
2. Add setItemPersistent method to save persistent data. Original setItem method is now used to save cached data.
3. Apply LRU policy on storage limit control.

add features to storage module

---

doc/demo/slider.md

* [ios] fix slider example href

---

doc/advanced/extend-to-android.md

-weex sdk support Moulde extend,

doc typo "Module"

---

html5/default/vm/compiler.js
html5/default/vm/directive.js
html5/test/unit/default/assets/static1.input
html5/test/unit/default/assets/static1.output
html5/test/unit/default/assets/static2.input
html5/test/unit/default/assets/static2.output
html5/test/unit/default/assets/static3.input
html5/test/unit/default/assets/static3.output
html5/test/unit/default/assets/static4.input
html5/test/unit/default/assets/static4.output
html5/test/unit/default/test.js
package.json

+ [jsfm] add static support

---

dist/weex-js-framework/package.json
html5/test/unit/default/test.js
html5/vdom/index.js
package.json

fix callAddElement callback -1

* [jsfm] fix callAddElement callback -1

---

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m

fix style line-height conflict with text-align

* [ios] fix style line-height conflict with text-align

---

html5/browser/base/component/index.js

test whether or not to trigger `appear` event in the next-tick after `onAppend` hook.

html5 test appear in next tick

---

html5/browser/extend/api/dom.js
html5/browser/utils/index.js

support `dom.addRule` for adding iconfont

html5 feature iconfont

---

doc/advanced/integrate-to-android.md

Correct typos

---

README.md
android/sdk/src/main/java/com/taobao/weex/ui/view/WXScrollView.java

在readme中展示各平台SDK最新版本的badge ，包括：    
jcenter内的[Android SDK](https://bintray.com/alibabaweex/maven/weex_sdk)
cocoapods内的[iOS SDK](https://cocoapods.org/pods/WeexSDK)
npm内的[HTML5 SDK](https://www.npmjs.com/package/weex-html5)

* [doc] add latest version badge

---

doc/components/slider.md
doc/faq.md
doc/references/common-style.md

+ [doc] add interval for slider
+ [doc] add `overflow` issue for android
+ [doc] add `border-width` issue

+ [doc] update doc for faq, slider, border-width

---

ios/sdk/WeexSDK.podspec

* [ios] fix update WeexSDK podspec version to 0.7.0

* [ios] fix update WeexSDK podspec version to 0.7.0

---

html5/default/app/bundle/define.js
html5/default/app/bundle/index.js
html5/default/app/ctrl/misc.js
html5/default/app/instance.js
html5/default/static/life.js
html5/test/unit/default/app/bundle.js
html5/test/unit/default/assets/clear-moduleA.input
html5/test/unit/default/assets/clear-moduleA.output
html5/test/unit/default/assets/clear-moduleB.input
html5/test/unit/default/assets/clear-moduleB.output
html5/test/unit/default/test.js

jsfm bugfix common modules

---

dist/weex-js-framework/package.json
html5/runtime/framework-rx.js
html5/vdom/index.js
package.json

* removed Rx framework temporarily util it fully open source and docs/examples ready
* adapted old native version which doesn't support `callAddElement`

[jsfm] v0.16.17

---

html5/browser/extend/api/globalEvent.js

Html5 feature global event

---

package.json

html5 update subversion

---

doc/modules/animation.md

* [doc] update doc for animation module

* [doc] update doc for animation module

---

doc/components/a.md

support onclick for A component and add tip for it

* [doc] add tip for A component

---

doc/SUMMARY.md
doc/modules/globalevent.md

Doc feature global event

---

ios/playground/Podfile
ios/sdk/WeexSDK/Sources/Component/WXSliderNeighborComponent.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h

1. fix playground Podfile  
2. remove c header file  include in WXUtility.h

* [ios] fix playground Podfile

---

html5/shared/console.js
html5/shared/promise.js
html5/shared/setTimeout.js
html5/test/unit/default/api/methods.js
html5/test/unit/default/app/ctrl.js
html5/test/unit/default/app/downgrade.js
html5/test/unit/default/app/index.js
html5/test/unit/default/app/register.js
html5/test/unit/shared/utils.js

Add more test case for:
+ register api methods
+ register modules
+ invalid version check
+ App.prototype
+ updateActions

[jsfm] Improve the test coverage for app instance

---

examples/index.we
examples/module/clipboard.we

1. bugfix clipboard
2. add clipboard to index

* [example] bugfix clipboard

---

ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.h
ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m
ios/sdk/WeexSDK/Sources/Manager/WXDatePickerManager.h
ios/sdk/WeexSDK/Sources/Manager/WXDatePickerManager.m

#1067 
经过讨论，决定改用符合html5标准方式实现，即增加input标签所支持的type，而非自定义module，这样h5端实现也简洁很多
需求版本 0.9.3
关联PR
html5 PR
https://github.com/alibaba/weex/pull/1480
android PR
https://github.com/sospartan/weex/pull/36

+ [ios] close #1067, add datepicker for 0.9.3requirement

---

html5/frameworks/legacy/app/ctrl/init.js
html5/test/case/basic/require.source.js

This feature may be a little rigorous, Should be carefully examined.

[jsfm] Wrap IFFE and use strict mode for js bundle

---

doc/modules/globalevent.md

add how to fire a global event on web platform.

doc fire a globalevent on web platform

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
ios/sdk/WeexSDK/Sources/Manager/WXDatePickerManager.m

修复weexsdk中 WXDatePickerManager 编译错误

Ios bugfix datepicker warning

---

doc/SUMMARY.md
doc/components/textarea.md

add doc for textarea component

*[doc] textarea

---

ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m

iconfont 的表现形式和安卓不一样，主要是url判断逻辑有问题
正确的逻辑
没有错误和地址存在，设置font并保留

Ios bugfix iconfont

---

doc/syntax/config-n-data.md

bugfix for config, need to be a json.

bugfix for config

---

ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m

* [ios] support setting userAgent

---

android/sdk/src/main/java/com/taobao/weex/appfram/storage/DefaultWXStorage.java
android/sdk/src/main/java/com/taobao/weex/appfram/storage/WXSQLiteOpenHelper.java

bug ： 
1. android.database.sqlite.SQLiteException: no such table: default_wx_storage (code 1): , while compiling: INSERT OR REPLACE INTO default_wx_storage VALUES (?,?,?,?);
2. android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.taobao.taobao/databases/WXStorage' to 'zh_CN'.

bug fix. retrieve sqliteDatabase fails.

---

ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.h
ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m
ios/sdk/WeexSDK/Sources/Module/WXDomModule.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

1. fix iconfont localsrc update
2.fix component rect info

* [ios] fix iconfont localsrc update && fix component rect

---

doc/tools/playground-app.md

* [doc] update playground doc

---

doc/SUMMARY.md

* [doc] add gesture to summary

---

android/commons/build.gradle
android/commons/src/main/java/com/alibaba/weex/commons/SimpleWeexActivity.java
android/commons/src/main/java/com/alibaba/weex/commons/WXAnalyzerDelegate.java
android/playground/app/build.gradle
android/playground/app/src/main/java/com/alibaba/weex/IndexActivity.java
android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java

https://github.com/weexteam/weex-analyzer-android
`Weex-Analyzer` provides several convenient tools such as Memory Monitor
to optimize your application. It's not available by default,
set `WXAnalyzerDelegate#DEBUG=true` to enable it

[android] feature weex-analyzer

---

ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m

Fix issue that if refresh is inserted before header,  header will not display.

* [ios] Don't insert section if subcomponent is not header or cell

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m

Ios bugfix textarea keyboard

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m

1.textarea 组件的placeholder 大小不可变，位置不对，有值的时候placehodler 仍旧显示
bug用例
http://weex.alibaba-inc.com/playground/1727409f5ba0d054d6930f9f3a99dcd9

+ [ios] fix textarea placeholder bug

---

ios/sdk/WeexSDK/Sources/Component/WXCellComponent.m
ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m
ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m

* Guard against NaN values with WXPixelType
* do not trigger display if frame has zero width or height

* [ios] Guard against NaN values with WXPixelType

---

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m

Ios bugfix nousecode

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m
ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.h

when keyboard pick up and change the rootview frame ,freeze rootview frame. when keyboard drop down , unfreeze rootview frame

Ios bugfix resetrootview

---

ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m
ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
ios/sdk/WeexSDK/Sources/Module/WXDomModule.m

* [ios] adapter onclick coordinate

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m

标准
http://gitlab.alibaba-inc.com/Jerry/api/blob/master/picker.md
测试用例
[picker]([单选picker例子](http://weex.alibaba-inc.com/playground/bd78c4e1a741cf9ca359cb3b59269b92)

+ [ios] add feature picker

---

ios/playground/WeexDemo/Scanner/WXScannerVC.m
ios/sdk/WeexSDK.podspec
ios/sdk/WeexSDK/Sources/Component/WXAComponent.m
ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.m
ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.h
ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m
ios/sdk/WeexSDK/Sources/Module/WXDomModule.m
ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m
ios/sdk/WeexSDK/Sources/Protocol/WXURLRewriteProtocol.h

1. support components load relative path resource
2. cancel simulator scanner

* [ios] support components load relative path resource

---

ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m

bugfix add register component Type

* [ios] bugfix add register component type

---

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m

fix #1664 
测试代码：
http://weex.alibaba-inc.com/playground/6c41fcdb28d1dda7a741f0aaa0766636

* [ios] bug fix 1664, add resetLoadmore on scroller & list.

---

package.json

+ upgrade weex-vue-framework to 2.0.6-weex.1.
+ update jsfm version (0.17.0-beta).

[jsfm] Upgrade weex-vue-framework version (2.0.6-weex.1)

---

ios/sdk/WeexSDK/Sources/Component/WXAComponent.m
ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m
ios/sdk/WeexSDK/Sources/Protocol/WXURLRewriteProtocol.h

fix compiler complain about warning

* [ios] fix compiler complain about warning

---

ios/sdk/WeexSDKTests/WXSDKEngineTests.m

* [ios] fix testComponentFactory

---

ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m

+ [ios] bugfix picker

---

ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m
ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m

bugfix component load rewriteurl

* [ios] bugfix component load rewriteurl

---

examples/module/picker-demo.we

* [example] bugfix picker max value

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m

Ios bugfix chinese not add

---

ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m

Ios bugfix picker crash

---

ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
ios/sdk/WeexSDK/Sources/Protocol/WXScrollerProtocol.h

#1782 
#1664 
fix list上resetLoadmore不生效。

* [iox] fix 1784.

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m

bugfix texture and input keyboard animation not with component. change UIKeyboardDidShowNotification to UIKeyboardWillShowNotification
现在viewwillload 是在createfinish之后没有之前的问题了，可以用UIKeyboardWillShowNotification

[ios] bugfix 1208 input keyboard

---

examples/component/input-demo.we

+ [example] add demo of focus & blur

---

ios/sdk/WeexSDK/Sources/Handler/WXNavigationDefaultImpl.m
ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

* [ios] bugfix cancel url uft8-encode

---

ios/sdk/WeexSDK/Sources/Handler/WXNavigationDefaultImpl.m
ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

Revert "* [ios] bugfix cancel url uft8-encode"

---

ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m

* [ios] image placeholder compatible

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m
ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m

* [ios] fontsize reset

---

doc/advanced/extend-to-ios.md

Remove some invisiable characters in document [extend-to-ios.md](https://github.com/alibaba/weex/blob/dev/doc/advanced/extend-to-ios.md)

* [doc] Remove invisiable characters

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m

add focus for textarea
bug fix :cursor auto to end

* [ios] add focus for textarea and bug fix cursor auto to end

---

examples/index.we
examples/module/picker-demo.we

[example] add picker example for playgound

+ [example] add picker example for playgound

---

examples/component/input-demo.we

- 补全input所有type的demo
- 添加focus()和blur()的demo

* [example] update the input demo

---

examples/component/slider-neighbor/silder-neighbor.we
ios/sdk/WeexSDK/Sources/Component/WXSliderComponent.m

fix bug:the index of slider component is invalid in less than two entries.

Ios feature 20161208 demo update

---

build/webpack.examples.config.js
package.json

The new version of weex-loader both support `*.we` and `*.vue`

[jsfm] updated weex-loader

---

examples/index.we
examples/module/componentRect.we

* [ios] add getComponentRect Example

* [ios] add getComponentRect Example

---

html5/render/browser/dom/componentManager.js

add finish events for module/component developers:
- weex:createfinish
- weex:updatefinish
- weex:refreshfinish
use these events:
```javascript
window.addEventListener('weex:createfinish', callback)
```

html5 add finish events for module developers.

---

ios/sdk/WeexSDK/Sources/Module/WXGlobalEventModule.m

add removeObserver for globalEvent module dealloc

*[ios] removeObserver in globalEvent module dealloc

---

ios/sdk/WeexSDK/Sources/Component/WXSliderNeighborComponent.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Module/WXGlobalEventModule.m

enable set neighbor-space for slider-neighbor

* [ios] enable set neighbor-space for slider-neighbor

---

ios/sdk/WeexSDK/Sources/Module/WXGlobalEventModule.m

add more annotation about fireglobalEvent

* [ios] add annotation about fireglobalEvent

---

ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m

给image组件的onload 事件增加image 的size
[image 组件获取图片大小 ios/android ](http://velocity.alibaba-inc.com/issues/3203)

+ [ios] add image size when image onload

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m

texture bug fix : when input change . the text content send to change

* [ios] texture bug fix : when input change . the text content send to change

---

examples/component/slider-neighbor/silder-neighbor.we

更改slider-neighobr的demo，原demo为测试用demo,写法有不规范的情况，有时会计算不准图片高度值。

Ios feature 20170118

---

ios/sdk/WeexSDK/Sources/Component/WXSliderNeighborComponent.m
ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m

remove items when view unload in slider-neighbor

* [ios] remove items when view unload in slider-neighbor

---

.wwprc
html5/render/browser/extend/components/neighbor.js
html5/render/browser/extend/components/neighbor/index.js
html5/render/browser/extend/components/neighbor/neighbor.css

add component `<slider-neighbor>`
- `neighbor-space`: 0 - 375
- `neighbor-alpha`: 0 - 1
- `neighbor-scale`: 0 - 1

[html5] support component slider-neighbor

---

doc/modules/picker.md

add picker doc for picker feature(0.9.4 已发版，同步更新picker文档)

+ [doc] add picker doc for picker feature

---

doc/modules/dom.md

add get doc for component rect Info

* [doc] add get doc for component rect Info

---

ios/playground/WeexDemo.xcodeproj/project.pbxproj
ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Component/WXComponent+GradientColor.h
ios/sdk/WeexSDK/Sources/Component/WXComponent+GradientColor.m
ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
ios/sdk/WeexSDK/Sources/Model/WXComponent.m
ios/sdk/WeexSDK/Sources/Utility/WXConvert.h
ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
ios/sdk/WeexSDK/Sources/Utility/WXType.h
ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m

support gradient-color, please review and merge this branch.

Ios feature gradient

---

doc/SUMMARY.md
doc/syntax/path.md

+ [doc] add path & url doc

---

ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

* [ios] change variable name to prevent conflicting with C++ keyword

---

ios/sdk/WeexSDK/Sources/Bridge/WXDebugLoggerBridge.m

* [ios] fix compile error.

---

html5/services/amd/index.js
html5/services/index.js

to support AMD methods `define` and `require`.

[Jsfm] add simple AMD service.

---

html5/frameworks/index.js
package.json

[jsfm] add Rax framework

---

ios/sdk/WeexSDK/Sources/Component/WXLoadingIndicator.m

There are some changes in loading indicator, please merge this branch.

* [ios] bugfix loading indicator crash.

---

cn/index.html
cn/index_m.html
index.html

also with trailing whitespace trimed

* [site] Fixed typo and replace emoji to html entities

---

doc/modules/navigator.md

Fix typo in navigator.md

---

ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.h
ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.h
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
ios/sdk/WeexSDK/Sources/Network/WXResourceRequest.h

[ios] added a new jsservice method -> registerService:withScriptUrl:WithOptions:

---

ios/playground/WeexDemo.xcodeproj/project.pbxproj
ios/playground/WeexDemo.xcodeproj/project.xcworkspace/contents.xcworkspacedata

* [ios] bugfix: playground cannot open

---

ios/sdk/WeexSDK/Sources/Controller/WXBaseViewController.m

modify bundleUrl to string type, fix the error ''Invalid type in JSON write (URL)

modify bundleUrl to string

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m

bugfix multi input or textarea maybe wrongly change root view

* [ios] bugfix multi input or textarea maybe wrongly change root view

---

html5/render/browser/extend/components/slider/index.js

add `weex-container` class name.

[html5] fix slider container's style.

---

ios/sdk/WeexSDK/Sources/Module/WXDomModule.m

bugfix rootView information  coordinate

* [ios] bugfix rootView information  coordinate

---

ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.h
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
ios/sdk/WeexSDK/Sources/Component/WXTransform.m
ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

* [ios]  fix issue that rotate(0) not work after rotate(>180degree)

---

ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.m

* [ios] bugfix moduleEvent compatible

---

ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.m
ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
ios/sdk/WeexSDK/Sources/Loader/WXResourceLoader.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.h
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_private.h

moduleEvent support variable value

* [ios] moduleEvent support variable value

---

ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_private.h

format module event callback data

* [ios] iOS feature 20170118

---

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m

case: http://dotwe.org/da0c8255a5cf79d384b2a2ebd7e5aa54
support textarea padding

* [ios] support textarea padding

---

ios/sdk/WeexSDK.podspec
ios/sdk/WeexSDK/Sources/Utility/WXDefine.h

* [ios] update weexSDK version

---

ios/sdk/WeexSDK.podspec
ios/sdk/WeexSDK/Sources/Utility/WXDefine.h

There are some changes in weexSDK, please merge this branch.

ios update weexSDK Version to 0.9.5

---

ios/sdk/WeexSDK/Sources/Handler/WXNavigationDefaultImpl.m

bugfix navigation pop animated value convert

* [ios] bugfix navigation pop animated value convert

---

ios/sdk/WeexSDK/Sources/Component/WXTransform.m
ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

Demo: http://dotwe.org/7d8e99a7d5dc8ee22e2437d6d8513fec

* [ios] fix issue that rotate 90->180->270 not work.

---

ios/sdk/WeexSDK/Sources/Module/WXNavigatorModule.m

* [ios] bugfix navigator open and close.

---

html5/render/browser/base/moduleEvent.js
html5/render/browser/render/register.js

support module event.
case: 
```javascript
var earth = require('@weex-module/earth')
earth.addEventListener('quake', function () { alert('better run quick !') })
```

[html5] support module event.

---

ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
ios/sdk/WeexSDK/Sources/Module/WXDomModule.m

1. bugfix onclick view use view frame
2. bugfix stick component getComponentRect

iOS feature 0.11

---

ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
ios/sdk/WeexSDK/Sources/Protocol/WXScrollerProtocol.h

scrollToElement add animated option

+ [ios] scrollToElement add animated option

---

ios/playground/WeexDemo/WXDemoViewController.m
ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.h
ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.h
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.h
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/WeexSDK.h

* [ios] trigger full gc only in debug mode
* [ios] public WXResourceRequestHandler

* [ios] Public WXResourceRequestHandler and  trigger full gc only in debug mode

---

ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m

* [ios]  check progressCallback of WXStreamModule before use it

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
ios/sdk/WeexSDK/Sources/Debug/WXDebugTool.h
ios/sdk/WeexSDK/Sources/Debug/WXDebugTool.m
ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
ios/sdk/WeexSDK/Sources/Manager/WXServiceFactory.m

Fixed when ios connect devtool restart runtime bug. When switch on debugTool will cached js service.

* [ios] fixed when devtool restart runtime missing js service

---

ios/sdk/WeexSDKTests/WXStorageTests.m

* Modify unit test of storage module

modify unit test of storage module

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
ios/sdk/WeexSDKTests/WXFloatCompareTests.m

+ [ios] add float compare function
we can compare as follow:
```javascript
float a = 0.1;
double b = 0.1;
NSLog(@"%d",WXFloatEqual(a, b));
NSLog(@"%d",WXFloatEqualWithPrecision(a, b,0.01));
a = 0.1;
b = 0.2;
NSLog(@"%d",WXFloatLessThan(a, b));
NSLog(@"%d",WXFloatLessThanWithPrecision(a, b,0.01));
NSLog(@"%d",WXFloatGreaterThan(b, a));
NSLog(@"%d",WXFloatGreaterThanWithPrecision(b, a,0.01));
```

+ [ios] add float compare function

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj

* [ios] set  WXModaolUIModule.h public

---

.wwprc
html5/render/browser/extend/components/richtext.js
html5/render/browser/extend/components/text.js

support component `<richtext>`.

[html5] support richtext.

---

doc/tools/cli.md

corrected typo

---

ios/playground/Podfile

*[ios] update podfile ,old cannot debug

*[ios] update podfile ,old cannot debug

---

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
ios/sdk/WeexSDK/Sources/Module/WXDomModule.m
package.json
test/run.sh
test/scripts/index.test.js
test/scripts/util.js

fix ios macaca test

---

ios/sdk/WeexSDK/Sources/Component/WXLoadingComponent.m

loading component 状态是 ‘show’的时候，不能持续展示在屏幕上

[ios] fix loading view cannot display when loading state is 'show'

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java

为input和textarea提供设置/获取文本选区的能力
Testcase:
http://dotwe.org/576201cb0c986e7ddb29626b373cc8db
PS. 需要依赖jsfm 0.19.6提供的component方法调用参数可传入callbackId的能力

+ [android] ability to set/get selection range on input

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/dom/WXStyle.java
android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/pesudo/PesudoStatus.java

一个微小的拼写错误：`pesudo` -> `pseudo`

* [android] fix typo pesudo -> pseudo

---

android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java

* [android] Use VisibleForTesting annotation to notify developers the accessibility of method.

* [android] VisibleForTesting annotation

---

README.md
ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
package.json

iOS 0.11 dev support wx unit

---

ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
ios/sdk/WeexSDK/Sources/Module/WXClipboardModule.m
ios/sdk/WeexSDK/Sources/Module/WXDomModule.m
ios/sdk/WeexSDK/Sources/Module/WXGlobalEventModule.m
ios/sdk/WeexSDK/Sources/Module/WXModalUIModule.m
ios/sdk/WeexSDK/Sources/Module/WXNavigatorModule.m
ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m
ios/sdk/WeexSDK/Sources/Module/WXStorageModule.m
ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m
ios/sdk/WeexSDK/Sources/Module/WXWebSocketModule.m

* [ios] because weex supports varying parameter, the value of callback maybe null. weex should protect callback(weex 支持了可变参数，callback 可能为空值，需要保护，和安卓同步)

* [ios] because weex supports varying parameter, the value of callback maybe null. weex should protect callback

---

ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m

* [ios] bug fix: when cell active ,the color cannot recovery(cell 用伪类的active，颜色无法恢复)

* [ios] bug fix: when cell active ,the color cannot recovery

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.m

* [ios] feature: check parameter:NSNumber contains int,float,double;object contains nsarray,nsstring,nsdictionary ;block should be block
对参数的类型校验：int,float,double为一类作为nsnumber,  nsarray,nsstring,nsdictionary为一类 作为对象校验，block 为一类block

* [ios] feature: check parameter:NSNumber contains int,float,double;object contains nsarray,nsstring,nsdictionary ;block should be block

---

ios/sdk/WeexSDK/Sources/Manager/WXComponentFactory.m

解决[config registerMethods];方法缺失

Fix issues 2464.

---

android/sdk/src/main/java/com/taobao/weex/ui/view/WXCircleViewPager.java

修复Slider中自动滚动的消息未在View销毁后被移除导致的上下文泄漏

* [android] fix slider memory leak

---

ios/sdk/WeexSDK/Sources/Utility/WXConvert.m

iOS feature support wx unit

---

html5/render/browser/extend/api/globalEvent.js

crash when add second listener for same global event

[html5] fix globalEvent.addEventListener error

---

examples/component/lengthunitwx-demo.we
html5/render/browser/base/component/valueFilter.js
html5/render/browser/render/index.js

add a new length unit of 'wx'. This is a platform based unit, just suitable for part-screen usage.
1. in html5 means x * devicePixelRatio.  
2. in Android means x * density (same as dp).
3. in iOS means x * scale.
so the weex will render the same size of views as the native does.

Feature add html5 wx length

---

html5/render/browser/base/component/operate.js

h5-render support pseudo class. https://github.com/alibaba/weex/issues/942

Html5 feature pseudo class

---

html5/render/vue/env/viewport.js
vue.html

[html5] fix bugs for viewport in some old android webkit browsers.

---

doc/package.json
doc/source/references/advanced/extend-jsfm.md
doc/source/references/advanced/extend-to-android.md
doc/source/references/advanced/extend-to-html5.md
doc/source/references/advanced/extend-to-ios.md
doc/source/references/advanced/index.md
doc/source/references/advanced/integrate-devtool-to-android.md
doc/source/references/advanced/integrate-devtool-to-ios.md
doc/source/references/js-service/index.md
doc/source/references/vue/difference-of-vuex.md
doc/source/references/vue/difference-with-web.md
doc/source/references/vue/index.md

Doc feature jsservice

---

doc/source/cn/guide/intro/devtools.md
doc/source/cn/references/common-style.md
doc/source/cn/references/components/image.md
doc/source/cn/references/components/input.md
doc/source/cn/references/components/textarea.md
doc/source/guide/intro/devtools.md
doc/source/references/common-style.md
doc/source/references/components/image.md
doc/source/references/components/input.md
doc/source/references/components/textarea.md

Added new doc: Using devtools.
Updated common style: Weex supports pseudo-classes and linear-gradient in the latest version.

* [doc] New doc: Using devtools.

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java

详情见iOS实现 https://github.com/alibaba/weex/pull/2516

+ [android] ability to set returnKeyType on input

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/ui/component/Scrollable.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/view/listview/ExtendedLinearLayoutManager.java
android/sdk/src/main/java/com/taobao/weex/ui/view/listview/WXRecyclerView.java
android/sdk/src/test/java/com/taobao/weex/ui/component/list/WXListComponentTest.java

调用`dom.scrollToElement`时支持指定是否使用滚动动画，默认开启动画。
Testcase：
**scroller** http://dotwe.org/weex/054ad1b8152ac7019cc079fd7fad9b99
**list** http://dotwe.org/weex/2b213db5fe83170bc228916df2aad546
iOS实现：https://github.com/alibaba/weex/pull/2289

+ [android] support the 'animated' option on scrollToElement

---

doc/source/references/advanced/extend-to-ios.md
doc/source/references/components/cell.md
doc/source/references/gesture.md

* Add docs for horizontal/vertical pan
* Add docs for extending ios sync module API

+ [doc]  Adding docs for 0.10.0 features.

---

examples/index.we
html5/render/browser/extend/components/input.js
html5/render/browser/extend/components/textarea.js
html5/render/browser/index.js
html5/render/vue/components/input.js
html5/render/vue/components/textarea.js
html5/render/vue/utils/func.js

+ [html5] support input/textarea selectionRange API

---

.eslintrc
examples/vue/components/slider.vue
html5/render/vue/components/slider/index.js
html5/render/vue/components/slider/indicator.js
html5/render/vue/env/index.js
html5/render/vue/mixins/style.js
html5/render/vue/styles/components.css

* fix slider's auto-play.
* fix indicator's rendering.
* fix indicator's style (except `item-color`, `item-selected-color`).
* fix style merging for vue-loader.

Html5 bugfix slider indicator

---

examples/vue/components/text.vue
html5/render/vue/components/text.js

* fix style `lines` of text.
* fix text example's line-height units.

[html5] fix text lines

---

html5/render/browser/extend/api/stream.js
html5/render/vue/env/index.js

[html5] fix jsonp callback of stream

---

android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java
android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderRadiusType.java
android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderWidthStyleColorType.java
android/sdk/src/test/java/com/taobao/weex/ui/view/border/BorderDrawableTest.java

* Use IntDef annotation to imply that certain parameters are int constant.
* Android Studio will give a warning if the specified parameter is not the valid constant value.

* [android] Add IntDef annotation

---

html5/render/vue/components/text.js

fix lines as a prop for text component.

[html5] fix text prop lines.

---

html5/render/vue/index.js

use `styleMixin` in production environment.

[html5] fix production mixin of style.

---

html5/render/vue/mixins/style.js

add protection code for none style rules.

[html5] fix style sheets.

---

examples/vue/showcase/itemlist.vue
html5/render/vue/components/image.js
html5/render/vue/mixins/base.js
html5/render/vue/mixins/scrollable.js
html5/render/vue/styles/components.css
html5/render/vue/utils/component.js
html5/render/vue/utils/index.js
html5/render/vue/utils/lazyload.js

* enable img's lazyloading.
* fix list's example.
* fix list overflow style.

[html5] feature img lazyload

---

ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

* [ios] fix custom font memory leak

---

html5/render/vue/components/scrollable/shared.js

* fix trigger of loading & refresh events.

[html5] bugfix loading

---

html5/render/vue/env/index.js
html5/render/vue/env/weex.js
html5/render/vue/index.js
html5/render/vue/modules/index.js
vue.html

wrap registerComponent api in weex instance.

[html5] feature support extending plugins.

---

html5/render/vue/styles/components.css

fix list/scroller's inertial scrolling.

[html5] bugfix inertial scrolling

---

doc/source/cn/guide/intro/using-vue.md
doc/source/guide/intro/using-vue.md

bugfix fix guide-intro using-vue doc

* [doc] bugfix fix guide-intro using-vue doc

---

html5/render/vue/styles/components.css

add styles for a as a general weex container, which means it is a flex layout box.

[html5] bugfix component a style

---

android/playground/app/build.gradle

exclude group: 'com.android.support', module: 'recyclerview-v7'

0.11 dev android uitest

---

examples/module/websocket-demo.we

* [example] bug fix: change websocket demo server

* [example] bug fix: change websocket demo server

---

ios/sdk/WeexSDK/Sources/Component/WXCellComponent.h
ios/sdk/WeexSDK/Sources/Component/WXCellComponent.m
ios/sdk/WeexSDK/Sources/Component/WXListComponent.m

keep the scroll position when inserting or deleting cells by adjusting the content offset

* [ios] keep the scroll position when inserting or deleting cells

---

html5/render/vue/mixins/base.js
html5/render/vue/utils/component.js
html5/render/vue/utils/lazyload.js

* fix lazyload during body scrolling

[html5] bugfix lazyload in body

---

html5/render/vue/components/image.js

* process placeholder src with processImgSrc function hook.

[html5] bugfix process placeholder

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/view/listview/WXRecyclerView.java

* [android] update list add attr keep-scroll-position

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java

Fixed remove a view contain a `fixed` child.
Test Case: http://dotwe.org/vue/b968a3b39fed998a563c5e033d4e1618

* [android] fix remove 'fixed' comp

---

android/sdk/src/main/java/com/taobao/weex/http/WXStreamModule.java

* [android] update WXStreamModule Determine whether the header is empty

---

android/sdk/src/main/java/com/taobao/weex/dom/WXDomModule.java
android/sdk/src/main/java/com/taobao/weex/ui/WXRenderStatement.java

* [android] update modify return value from String to float

---

html5/render/vue/components/image.js
html5/render/vue/mixins/base.js
html5/render/vue/mixins/scrollable.js
html5/render/vue/utils/func.js
html5/render/vue/utils/index.js
html5/render/vue/utils/lazyload.js
html5/render/vue/utils/type.js

* use throttled lazyloading to reduce javascript executing time.
* get throttle lazyload func for separate target and separate waiting time.

[html5] use throttled lazyloading to reduce javascript executing time.

---

html5/render/vue/components/slider/index.js
html5/render/vue/components/slider/indicator.js
html5/render/vue/components/slider/slideMixin.js
html5/render/vue/utils/func.js
index.html
vue.html

* fix indicator's style.
* support slider's scrollstart, scrollend and scroll event.
* add weex-viewport meta tag to entry html files.

[html5] support slider's scrollstart, scrollend and scroll events.

---

examples/vue/components/list.vue

* fix appear events in list example for invalid accessing of index.

[example] fix appear events handlers.

---

examples/vue/components/list.vue
examples/vue/components/marquee.vue
examples/vue/components/scroller.vue
examples/vue/components/slider.vue
examples/vue/include/example-list.vue
examples/vue/include/marquee.vue
examples/vue/include/slider-page.vue
examples/vue/include/tabbar.vue
examples/vue/modules/stream.vue
examples/vue/showcase/include/banners.vue
examples/vue/showcase/include/category.vue
examples/vue/showcase/include/goods.vue
examples/vue/showcase/include/match.vue
examples/vue/showcase/include/scene.vue
examples/vue/showcase/itemlist.vue
examples/vue/syntax/script-component.vue
examples/vue/syntax/script-events.vue
examples/vue/syntax/script-lifecycle.vue
examples/vue/syntax/template-repeat.vue

Fix some example error with `vue` .

* [example] fix vue examples error

---

ios/sdk/WeexSDK/Sources/Component/WXListComponent.mm

* [ios | feat] iOS15 adapter for list
1.  header extra padding
2. cell in list may disappear

[ios | feat] iOS15 adapter for list

---

ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m

PostMessageFormat:
`postMessage([{"arg1": "xxx", "arg2": 100}, "origin"]);`
Demo:  http://dotwe.org/vue/b7d6c6875ff7ae5ad90a5d84d0d46dbb

[ios] fix: web component support h5 postMessage to weex

---

android/sdk/src/main/java/org/apache/weex/WXSDKInstance.java
android/sdk/src/main/java/org/apache/weex/WXSDKManager.java
android/sdk/src/main/java/org/apache/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/org/apache/weex/common/WXErrorCode.java

[Android]Feat:add InitListener

---

android/sdk/src/main/java/org/apache/weex/ui/component/AbstractEditComponent.java

[Android]fix keyboardEventListener leak

---

WeexSDK.podspec

* Demo:
refer: https://github.com/alibaba/weex/commit/e3ce66159d193e3a73cf946653bb48bab06294c1

[ios] remove eagle's deprecated code
