alibaba/weex

html5/browser/componentManager.js
add protective code: none checking for null object lead to exceptions
=> html5 hotfix fire event

.gitignore, build/config.frameworks.js, build/webpack.browser.config.js, build/webpack.native.config.js, html5/runtime/.eslintrc, html5/runtime/framework-weex.js, html5/runtime/index.js, html5/test/unit/default/runtime.js, package.json
Now we can use `npm run build:config` to generate `html5/runtime/frameworks.js` (this file has been ignored by git now).
This command will find all the `framework-*.js` files in `html5/runtime/` folder and register each of them to the generated file.
``` js
// built by npm run build:config
import * as Weex from '../default'
import * as Rx from 'weex-rx-framework'
export default {
Weex,
Rx
}
```
You can also run it like `npm run build:config -- weex,rx` to filter which frameworks we will include.
Be default the generated file `html5/runtime/frameworks.js` not existed but when we run `npm run build:native`,  `npm run build:browser` or  `npm run build` it will init once if the file hasn't been built.
=> [jsfm] new mechanism for build frameworks

html5/default/app/bundle.js, html5/default/app/ctrl.js, html5/default/app/index.js, html5/default/core/state.js, html5/default/vm/compiler.js, html5/default/vm/directive.js, html5/default/vm/dom-helper.js, html5/default/vm/events.js, html5/default/vm/index.js, html5/test/unit/default/app/bundle.js, html5/test/unit/default/app/ctrl.js, html5/test/unit/default/app/index.js, html5/test/unit/default/vm/compiler.js, html5/test/unit/default/vm/directive.js, html5/test/unit/default/vm/dom-helper.js
e.g.
```javascript
Vm.prototype._xxx = function (a, b, c) {
// this
}
function Vm() {
this._xxx(1, 2, 3)
}
```
will be converted to:
```javascript
function xxx (vm, a, b, c) {
// vm
}
function Vm() {
xxx(vm, 1, 2, 3)
}
```
benefits:
1. protect the private method not exposed to developer
2. easy to trace the method source through import
3. easy to test
4. possible to minify the name (prototype member names cannot be minified)
=> [jsfm] make private method as functional as possible

android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java
the hot reload will not work if we change the ws port through weex tool-kit  
how to fix it :
weex tool-kit add ws port into the js bundle url as a parameter, So the playground can get the wsport, Then hot reload can work normally. 
I have pull a request to weex tool-kit  https://github.com/weexteam/weex-toolkit/pull/7
weex 命令行在修改 wsport 的情况下, playground 就无法 hotreload 了
给 weex tool-kit 也提交了一个 pr, https://github.com/weexteam/weex-toolkit/pull/7
意图就是让weex tool kit将 wsport 当做参数传过来, 让playground 可以解析到 wsport, 这样就可以继续 hotreload 了
=> Pass hotreload port as parameter

html5/default/vm/compiler.js, html5/test/unit/default/vm/vm.js
Before it fixed, when the array item with the same key updated but not the same ref, the data binding of the child properties will be lost. Because the data binding still on the old data ref.
Now the new ref data will be bound automatically so the bug has been fixed.
```javascript
// init data
data: {
list: [{x: 1}, {x: 2}, {x: 3}]
}
// update
this.list[0].x = 4 // it works both before and after this bugfix
this.list = [{x: 1}, {x: 2}, {x: 3}] // new data refs in this.list
this.list[0].x = 4 // it only works after this bugfix
```
=> [jsfm] fixed repeat bug when update values with new object references

build/nightwatch.config.js, package.json
circleci fails due to selenium-server's version disagreement with nightwatch config file. Try to specify the exact version within the config file in the package.json file, not allowing version auto-updating.
=> fix e2e test ci

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
Just as the title. When `callNative(instanceId, tasks)` called in JavaScript (without 3rd parameter), the 3rd parameter will be finally converted into a string `"undefined"` to `WXBridgeContext.m` and not be skiped. So another `callJS(instanceId, { type: "callback", args: ["undefined"] })` will be called back into JavaScript. And then infinite loop between like `callNative(instanceId, updateFinish)` and `callJS(instanceId, "undefined")` on and on...
As the callback feature not be used in JS Framework any more, to prevent this unexpected thing happens in the future. So I added `![callback isEqualToString:@"undefined"]` here and especially as the first condition. And then `![callback isEqualToString:@"-1"]` as the second. Actually the falsy `callback` never happens but as the consideration …
=> [ios] improved compatibility of callNative callback id

html5/browser/scroll.js
stop using `arguments.callee` in `requestFrame()` callback function.
created a named function to do the same thing, and pass it to the `requestFrame()`.
=> fix error in strict mode for scroll.js

examples/component/scroller-demo.we
* fix '＝' with '='.
* with this typo fixed, the `append=tree` worked, but it appears to confront another bug from jsfm, that the `Documenet.prototype.getRef` seems not working in tree mode.
=> example fix typo

html5/test/unit/default/assets/reset-style.input, html5/test/unit/default/assets/reset-style.output, html5/test/unit/default/test.js, html5/vdom/index.js
Reset the element's existing class styles, while it changes the class name. According to CSS spec, I use the empty string to reset the style.
See the [issue #397](https://github.com/alibaba/weex/issues/397).
=> + [jsfm] reset existing class styles before setting new styles

html5/shared/console.js
Add `off` log level to prevent all console outputs. See details in #966 .
=> + [jsfm] Add `off` log level to prevent all console outputs

dist/weex-html5/index.html
fix the problem in this issue. https://github.com/weexteam/weex-toolkit/issues/15
Note: this pr will have no influence on current developing branches, since its updating file is in the `dist` path.
=> html5 fix missing viewport meta in dist package

html5/default/app/ctrl/misc.js, html5/default/vm/index.js
Destroy the `vm` property recursively when destroy an app instance.
Set `app.vm = null` works well in most cases, but if developer cache the sub vm on somewhere (e.g. window), it may not destroyed entirety.
=> + [jsfm] Make the destroy logic of app instance more reliable

android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
InitConfig中设置的framework，应该在SDK初始化的时候使用
=> sdkmanager initScriptFramework use InitConfig framework field

html5/browser/runtime/app/ctrl/init.js, html5/default/app/ctrl/init.js, html5/default/core/observer.js, html5/default/vm/index.js
supported `weex-x` in the future
1. exported `__weex_viewmodel__` to instance env.
2. added API `Vm.set` and `Vm.del`.
3. added API `Vm.prototype.$watch`.
4. supported `new Vm` without app or document (so the `compile()` process will be skipped).
Test case will more depend on `weex-x` [examples](https://github.com/Jinjiang/weex-x/tree/master/examples/src) and [test](https://github.com/Jinjiang/weex-x/blob/master/test/index.js)
Thanks.
=> [jsfm] supported weex-x in the future

html5/default/core/dep.js, html5/default/core/watcher.js
In data-bing logic, the `prevTarget` will store the last watcher which couldn't be destroyed while switching app instance. And the prevTarget state is dismatched when evaluating computed lazy watcher.
+ change prevTarget to a stack
+ move the target operation to dep.js
See more details at [vue issue #3133](https://github.com/vuejs/vue/issues/3133)
=> [jsfm] Fix watcher dismatched bug between multi instance

html5/browser/utils/index.js
* add the object.assign polyfill back in case the weex bundle is transformed by the old versions of weex-loader.
=> html5 add object assign polyfill

html5/test/unit/vdom/index.js, html5/test/unit/vdom/listener.js, html5/vdom/index.js
Supported `Element.prototype.setAttr(key, value, false)` & `Element.prototype.setStyle(key, value, false)` to force update attribute or style. For some reasonable Rx virtual-DOM use case from @yuanyan
=> [jsfm] supported force update attr/style in vdom

html5/default/app/ctrl/misc.js, html5/default/vm/events.js
Add `destroyed` lifecircle on vm. Developers can add extra cleanup works here to prevent memory leak.
Two notices:
1. The `destroyed` hook will be emitted before doing internal cleanup procedures.
2. Child vms' `destroyed` hook will be emitted before there parent's.
=> + [jsfm] Add `destroyed` lifecircle #862

html5/browser/base/component/sticky.js, html5/browser/render/index.js, index.html
* fix `sticky` both in downgrade root and scrollable components.
* support `downgrade: ['root']` in weex's init function
=> html5 bugfix sticky

doc/components/a.md, doc/components/special-element.md, doc/modules/clipboard.md, doc/modules/storage.md, doc/references/text-style.md
The "This property doesn't  **guarteen** the given font will always be set to the text. If the specified font cannot be found at the device, a typeface fallback will **occurr** and the default typeface will be load." has two spelling mistake,should be
>  "guarteen" to "**guarantee**",
> "occurr" to "**occur**".
In the special-element.md,should be
> "outlest " to "**outlet**".
=> Update Doc chapter(spelling mistake)

android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java, android/sdk/src/main/java/com/taobao/weex/utils/WXLogUtils.java
Add line number (e.g. `(WXSDKInstance.java:752) `) before log content when method `WXEnvironment.isApkDebugable()` return `true`    
It provide the ability to hyperlink to code, looks like this:    
same as #1091
=> + [android] add line number before log content

html5/browser/base/component/lazyload.js
In the method `makeImageLazy`, the lazyload firing  is processed immediately. It should be delayed to the next tick since the dom is not ready yet. This should fix the bug that the last image in a repeat list is missing.
=> html5 fix img lazyload

android/sdk/src/main/java/com/taobao/weex/ui/component/WXSliderNeighbor.java
上一版本的slider-neighbor 对中间cell的宽度有要求(必须为容器宽度-50)，否则有可能超出部分被截断。这里修复了这个bug
=> slider-neighbor bug fixed.(split problem)

ios/sdk/WeexSDK.xcodeproj/project.pbxproj, ios/sdk/WeexSDK/Sources/Utility/WXConvert.m, ios/sdk/WeexSDKTests/WXConvertTests.m
text的lines属性值的转换由WXConvert负责，且对应到方法
```
WXConvert:NSUInteger:
```
而该方法是由宏定义生成的，该宏定义的代码如下：
```
#define WX_NUMBER_CONVERT(type, op) \
+ (type)type:(id)value {\
if([value respondsToSelector:@selector(op)]){\
return (type)[value op];\
} else {\
WXLogError(@"Convert Error:%@ not respond selector:%@", value, @#op);\
}\
return 0;\
}
```
* 当text的lines属性值设置为string时，WXConvert的相关转换方法的入参为string类型，无法响应以下中unsigned开头的方法。
* 当text的lines属性值设置为数值类型时，WXConvert的相关转换方法的入参为Number类型，可以响应以下中unsigned开头的方法。
```
WX_NUMBER_CONVERT(BOOL, boolValue)
WX_NUMBER_CONVERT(int, intValue)
WX_NUMBER_CONVERT(short, shortValue)
WX_NUMBER_CONVERT(int64_t, longLongValue)
WX_NUMBER_CONVERT(uint8_t, unsignedShortValue)
WX_NUMBER_CONVERT(uint16_t, unsignedIntValue)
WX_NUMBER_CONVERT(uint32_t, unsignedLongValue) …
```
=> * [ios] fix #1188, support for converting string to NSUInteger.

html5/browser/extend/components/image/index.js, html5/browser/extend/components/scrollable/loading/index.js, html5/browser/extend/components/scrollable/refresh/index.js, html5/browser/extend/components/scrollable/scrollable.js, html5/browser/extend/components/spinner/index.js, html5/browser/extend/components/textarea.js, html5/browser/extend/components/video/index.js, package.json
Adding multiple class names through `classList.add()` is not supported for some browsers. For examples: `element.classList.add('weex-ct', 'weex-element')` is only adding `weex-ct` to the element. For now this bug is discovered on android UC browser only (including the latest `v11.xxx` version).
=> html5 fix class name

ios/playground/WeexDemo/WXDemoViewController.m
打开url的时候需要先判断一下有没有参数，以决定拼接random参数是用？还是&连接，要不然url会拼错
=> [ios] bugfix - url : 打开url的时候需要先判断一下有没有参数，以决定拼接random参数是用？还是&连接

android/sdk/src/main/java/com/taobao/weex/appfram/storage/DefaultWXStorage.java, android/sdk/src/main/java/com/taobao/weex/appfram/storage/IWXStorage.java, android/sdk/src/main/java/com/taobao/weex/appfram/storage/IWXStorageAdapter.java, android/sdk/src/main/java/com/taobao/weex/appfram/storage/WXSQLiteOpenHelper.java, android/sdk/src/main/java/com/taobao/weex/appfram/storage/WXStorageModule.java, android/sdk/src/test/java/com/taobao/weex/appfram/storage/WXStorageModuleTest.java
1. Add Total storage limit to 50M. No limit in original version.
2. Add setItemPersistent method to save persistent data. Original setItem method is now used to save cached data.
3. Apply LRU policy on storage limit control.
=> add features to storage module(android)

doc/README.md
Fix the 404 problem of accessing the links of README file. The relative path is wrong.
=> The relative path of the link of the README file in doc folder is wrong

html5/test/unit/vanilla/index.js
Add unit test cases for `frameworks/vanilla` , all coverage (includes statements, branches, functions, lines) are 100%.
=> [jsfm] Add unit tests for vanilla framework

doc/syntax/comm.md
since `this.$()` is deprecated and should use `this.$vm()` to get a vm instance.
=> doc bugfix: this.$() -> this.$vm()

ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
原有的IOS版本不支持三位的颜色值。将#fff变成了红色。 这个分支修复了这个问题。支持三位的颜色值。
=> * [ios] fix #1192, #FFF display error in iOS

html5/render/browser/extend/api/dom.js
Usage :
```js
var dom = require('@weex-module/dom')
module.exports = {
ready: function() {
var elem = this.$el('elementId')
dom.getComponentRect(elem, function(info) {
// got the component layout information
console.log(info)
})
}
}
```
Data structure of `info` :
```js
// success
{
result: true,
size: {
width  : Number
height : Number,
top    : Number, // distance from component top edge to the top of viewport
left   : Number, // distance from component left edge to the left of viewport
right  : Number, // distance from component right edge to the left of viewport
bottom : Number, // distance from component bottom edge to the top of viewport
}
}
// fail
{
result: false,
errMsg: 'Illegal parameter'
}
```
=> [html5] add getComponentRect api for dom module

examples/component/input-demo.we, html5/render/browser/extend/components/input.js
#1067 
经过讨论，决定改用符合html5标准方式实现，即增加input标签所支持的type，而非自定义module，这样h5端实现也简洁很多
需求版本 0.9.3
iOS PR
https://github.com/alibaba/weex/pull/1478
android PR
https://github.com/sospartan/weex/pull/36
=> + [html5] close #1067, add datepicker

start
Add missing shebang for `start`.
Run `./start` without shebang in `fish` shell got:
```
Failed to execute process './start'. Reason:
exec: Exec format error
The file './start' is marked as an executable but could not be run by the operating system.
```
=> * [all] add missing shebang

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java, android/sdk/src/main/java/com/taobao/weex/appfram/storage/DefaultWXStorage.java, android/sdk/src/main/java/com/taobao/weex/appfram/storage/WXSQLiteOpenHelper.java, android/sdk/src/test/java/com/taobao/weex/appfram/storage/DefaultWXStorageTest.java
1. WXSQLiteOpenHelper是单例的， 且持有Context引用，不当使用可能会引起内存泄露.  （虽然目前传入的是WXEnvironment.sApplication）
2. WXPerformance#templateUrl字段从未赋值，我觉得可以在WXSDKInstance#renderByUrl中进行赋值.
=> bug fix.WXSQLiteOpenHelper mem leak

html5/render/browser/extend/api/stream.js
支持html5 中 stream module在跨域cors情况下带cookie
和[https://github.com/alibaba/weex/pull/1509](https://github.com/alibaba/weex/pull/1509)一样，更正了提交分支
=> * [html5] stream module  cors cookie support

ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.h, ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
WXSDKInstance 的rootView 定义 readwrite 属性，有可能会被如下使用
xxSDKInstance.rootView= self;
然后 在render 完成 oncreate返回的优势 rootview
会出现 self add self的问题
因此改成 readonly,后期有好的解决方案再改成readwrite
=> * [ios] fix WXSDKInstance rootview bug

ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
第二个commit是
```
+ (UIColor *)UIColor:(id)value
```
value为nil时，
会返回如下color
```
color = [UIColor colorWithRed:255 green:255 blue:255 alpha:1.0];
```
但应该是要返回nil的
=> * [ios] fix issue about WXConvert 's UIColor method

html5/render/browser/render/index.js
deviceWidth use window.innerWidth and deviceHeight use window.innerHeight.
=> html5 deviceWidth and deviceHeight of getConfig.env use real pixel value

html5/frameworks/legacy/app/index.js, html5/frameworks/legacy/index.js, html5/render/native/index.js, html5/runtime/index.js, html5/shared/console.js, html5/shared/freeze.js, html5/shared/index.js, html5/shared/setTimeout.js, html5/test/case/tester.js, html5/test/case/throws/global-variable1.source.js, html5/test/case/throws/global-variable2.source.js, html5/test/case/throws/global-variable3.source.js, html5/test/unit/default/runtime.js, html5/test/unit/shared/console.js, html5/test/unit/shared/index.js
Freeze those objects:
+ Internal objects
+ Vm
+ App
+ Element
+ Comment
+ Listener
+ App.prototype
+ Document.prototype
+ Element.prototype
+ Comment.prototype
+ Listener.prototype
+ Build-in objects
+ Object
+ Array
+ Object.prototype
+ Array.prototype
+ String.prototype
+ Number.prototype
+ Boolean.prototype
+ Error.prototype
+ Date.prototype
+ Math.prototype
+ RegExp.prototype
> Once the object is frozen, there has no chance to unfreeze it.
In addition, because we use strict mode in the js bundle, modify those frozen objects will throw a `TypeError`.
=> [jsfm] Freeze the prototype of intrenal and build-in objects

build/rollup.config.js
Add the missing `setTimeout` in the banner for Android V8.
@sospartan @fkysly Please review.
=> [jsfm] Add the missing setTimeout for Android

ios/sdk/WeexSDK/Sources/Manager/WXDatePickerManager.m
由于没有使用WXConvert 转换，某些情况会让datepicker crash
=> * [ios] fix bug datepicker no update and crash

html5/render/browser/extend/api/stream.js
经过确认之前stream module  cors cookie support中的 withCrendentials这个单词拼错了，需要改成withCredentials
=> * [html5] stream module  cors cookie support fixbug

ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m, ios/sdk/WeexSDK/Sources/Module/WXPickerModule.h, ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m
在千牛的工作台模块中添加选择功能的时候
没有通用性的picker，千牛无法实现城市的选择，订单搜索条件过滤等功能
期望：
实现通用性的picker
解决方案：
实现picker组件
具体方案及接口
组件名字
picker
普通单选选择器:
属性名 | 类型 | 默认值 |说明
----|------|----|----
items | Array  | []| 传给picker的items数组
index | int  | 0| 是数字，表示选择了 items 中的第index个值，从0开始。
function | 回调 |  | 用户点击确定后，返回结果 index
使用例子
```js
pick:function (e) 
{
var picker = require('@weex-module/picker');
var items = new Array("Saab","Volvo","BMW");
var index = 0;
var self = this;
picker.pick(items,index,function (index) {
var value = items[index];
});
}
```
相关PR
[android picker 40](https://github.com/sospartan/weex/pull/40)
参考 http://velocity.alibaba-inc.com/issues/3034
=> Ios feature picker

html5/render/browser/extend/components/image/index.js, package.json
add `placeholder` attribute support for image.
demo:
```html
<template>
<div>
<image
style="width:320;height:100;"
src="//xxxxxxx.com/xx.jpg"
placeholder="//img.alicdn.com/simba/img/TB1l5R_OXXXXXcrXpXXSutbFXXX.jpg"></image>
</div>
</template>
```
the `src` is invalid, and it will use the `placeholder` image instead.
=> Html5 feature image placeholder

build/build.js, html5/frameworks/legacy/app/downgrade.js, html5/shared/index.js, html5/shared/promise.js, package.json
Rollup mistakenly eliminated few functions by tree shaking. Use a little tricks to make it works well.
+ Remove the usage of `this` in `downgrade`, just call the method directly.
+ Import promise hack (for iOS) before its polyfill.
=> [jsfm] Fix the rollup tree shaking accuracy

bin/commit-msg.sh
As described in #1567 , use `.` instead of `[^\n]` in `bin/commit-msg.sh`.
=> Fix the regular expression of commit message

html5/frameworks/legacy/app/ctrl/init.js
Javascript strict mode can prevent developer from creating global variables by accident, but it can't stop developer creating global variables intentionally (such as `global.cache = {}`).
But if we wrap a function like this:
```js
(function (global) {
"use strict";
/* function body */
})( Object.create(this) )
```
The `global` variable which js bundle can get is `Object.create(global)` in fact. It can access all global properties, however, add or modify properties on it will not affect the real global, and it will be cleared when the instance is destroyed.
=> [jsfm] Mock the 'global' variable for js bundle

html5/frameworks/legacy/api/methods.js, package.json
Fix the `npm run build` script.
`npm run build:examples:vue` is removed, just use `npm run build:examples` instead.
=> [jsfm] Fix the npm run build script

ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
=> * [ios] fix #1587,修复读取img的placeholder属性时采用驼峰式命名导致无法设置placeholder的问题

html5/frameworks/legacy/app/ctrl/init.js
To avoid conflict of document detection in JS bundle. For example `document.createTextNode('')` for `Promise` polyfill will go error.
=> [jsfm] Removed document parameter from running js bundle.

ios/sdk/WeexSDK/Sources/Module/WXClipboardModule.m
clipboard 返回的数据格式不对，很安卓不一样
js预期接收对象，现在是一个字符串
=> + [ios] bugfix:clipboard callback value not rgiht

html5/frameworks/legacy/api/methods.js
For the Component method api, if we decide to use the feature in #1604 , the modification in #1597 should be reverted.
=> [jsfm] Revert the modification of vm.$el

build/rollup.config.js, package.json
Replacing `process.env` into `"dev"` or `"production"` in order to enable tree-shaking in rollup.
* `npm run build:native` will output a production version
* `rollup -c build/rollup.config.js --dev` or `npm run build:native -- --dev` will output a dev version
The sourcemap will be inlined in dev version but the production version will not.
=> [jsfm] supported replacing process.env

ios/sdk/WeexSDK/Sources/Component/WXEmbedComponent.m
when network error or file read error, callback may be asynchronous
=> [ios] fix crash on async‘s callback

ios/sdk/WeexSDK.podspec, ios/sdk/WeexSDK.xcodeproj/project.pbxproj, ios/sdk/WeexSDK/Sources/Utility/WXDefine.h
=> * [ios] update sdk version to 0.9.4

ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m
现在增加了datepicker 和time picker，重用会出现问题，暂时先去掉picker重用的view
=> Ios bugfix picker reuse

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m
之前代码不小心更改了_updateAttributesOnComponentThread ，造成多态失效，现在修复
=> Ios bugfix resetstyles

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
fix bug: text area cursor auto go to end .
reason: if attributes[@"value"] is exist. _updateAttributesOnMainThread will change textview text.the cursor go to end. 
solution: save the  textview  selectedRange , when set textview.text ,correct it
=> [ios] text area cursor auto go to end

ios/sdk/WeexSDK/Sources/Handler/WXNavigationDefaultImpl.m, ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m, ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
bugfix iconfont load, support woff
=> * [ios] bugfix iconfont load, support woff

ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h, ios/sdk/WeexSDK/Sources/Component/WXLoadingIndicator.m, ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m, ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m, ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m, ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m, ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m, ios/sdk/WeexSDK/Sources/Model/WXComponent.h, ios/sdk/WeexSDK/Sources/Model/WXComponent.m, ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m
样式改变的时候，高度不设置，采用fontsize的，和安卓，h5 统一
=> [ios] when style change , text height not set , text height should same as fontsize

ios/sdk/WeexSDK/Sources/Module/WXClipboardModule.m
1. Modify WXClipboardModule by dispatching to a default queue when using UIPasteboard to avoid blocking main queue under iOS10 & macOS Sierra.
=> add targetqueue to clipboard

html5/render/browser/base/component/index.js, html5/render/browser/dom/appearWatcher.js
fix appear's bug when inner scroller has no height specified.
case:
```html
<template>
<div>
<text>{{value}}</text>
<scroller>
<div class="container" repeat="{{(k, v) in itemList}}">
<text class="thumb title" indexv="{{k}}" onappear="test(k)">{{v.title}}</text>
</div>
</scroller>
</div>
</template>
<style>
.container {flex-direction: row;}
.thumb {width: 200; height: 500;}
.title {flex: 1; color: #ff0000; font-size: 48; font-weight: bold; background-color: #eeeeee;}
</style>
<script>
module.exports = {
data: {
itemList: [
{itemId: '520421163634', title: 'title1'},
{itemId: '522076777462', title: 'title2'}, 
{itemId: '520421163634', title: 'title3'},
{itemId: '522076777462', title: 'title4'}, 
{itemId: '520421163634', title: 'title5'},
{itemId: '522076777462', title: 'title6'}, 
],
value:0 …
```
=> [html5] fix appear when scroller has a height bigger than view height.

html5/render/browser/extend/components/video/index.js
video tag add `playsinline` by default to prevent auto changing to fullscreen displaying.
=> [html5] add playsinline by default for video

html5/frameworks/legacy/app/ctrl/init.js, html5/test/case/basic/global-weex-object.output.js, html5/test/case/basic/global-weex-object.source.js, html5/test/case/tester.js
* `weex.config` === `this.$getConfig()`
* `weex.require('xxx')` === `__weex_require__('xxx')` === `require('@weex-module/xxx')`
And more low-level APIs
* `weex.define` === `__weex_define__`
* `weex.document` === `__weex_document__`
* `weex.bootstrap` === `__weex_bootstrap__`
* `weex.Vm` === `__weex_viewmodel__`
And they all work in both `*.we` files and `*.js` files
=> * [jsfm] create a global Weex object for each JS bundle scope instead of __weex_xxx__

html5/render/browser/extend/components/video/index.js
fix `uncaught (in promise) DOMException: The play() request was interrupted by a new load request.`
=> [html5] fix uncaught dom exception for video.play.

ios/sdk/WeexSDK/Sources/Component/WXSliderComponent.m
测试demo:http://weex.alibaba-inc.com/playground/fe233c18bb0bd24b2dfe7076c772eff7
解决方案：
scroll过程中通过onscroll事件回调，传回x轴偏移比例。前端监听onscroll事件，并设置精度值：0--1之间。native端判断偏移比例超过精度就进行一次回调。比如：精度0.1，正常会回调8或9次。scroll达到page宽度时，可能不回调。所以前端要监听onchange事件，保证currentPage值正确。
=> Ios feature 20170118 slider onscroll

android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
WXRenderStatement has transform offset,do not transform at WXScroller again.
=> * [android] bugfix scroller offset transform twice

ios/sdk/WeexSDK/Sources/Module/WXGlobalEventModule.m
bugfix globalEvent removeObserver don't need specify target
=> * [ios] bugfix globalEvent removeObserver don't need specify target

ios/sdk/WeexSDK/Sources/Manager/WXInvocationConfig.m
jsfm 传递得参数小于native函数指定个数，ios将获取的value设置到指定的参数上，其他的参数采用默认值(when jsfm send variable parameter that Less than native parameter number , iOS will set the parameter the gain value and other parameters which not set with default value )
变量类型(parameter  type) | 默认值(default value) |
----|------|
string | nil  |
float |0 |
double |0 |
int |0 |
nsdictionary |nil |
NSArray|nil|
WXModuleCallback|null|
=> + [ios] feature support jsfm variableparameter

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m, ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m, ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m, ios/sdk/WeexSDK/Sources/Utility/WXConvert.h, ios/sdk/WeexSDK/Sources/Utility/WXConvert.m, ios/sdk/WeexSDK/Sources/Utility/WXType.h, ios/sdk/WeexSDK/Sources/Utility/WXUtility.h, ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
[#3167](http://velocity.alibaba-inc.com/issues/3167)DSL设置了字重，weex sdk需要提供相关字重显示(weex sdk support font weight when DSL set font weight)
用户在we文件中设置font-weight,三端可以设置相关的字重(set in dsl, native should show text change with font weight)
jsfm传回字重（normal,bold,100-900）(jsfm send font weight normal,bold,100-900)<br/>
ios将字重对应到系统字库的字重上面,全部支持(ios show text as dsl font weight, ios support nine different font weight)<br/>
字重对应表(font weight chart)
jsfm | ios |value
----|------|------|
100|UIFontWeightUltraLight|-0.8
200|UIFontWeightThin|-0.6
300|UIFontWeightLight|-0.4
400|UIFontWeightRegular|0
500|UIFontWeightMedium|0.23
600|UIFontWeightSemibold|0.3
700|UIFontWeightBold|0.4
800|UIFontWeightHeavy|0.56
900|UIFontWeightBlack|0.62
normal|UIFontWeightRegular|0
bold|UIFontWeightBold|0.4
| ios system|
----| …
=> + [ios] weex sdk support font weight when DSL set font weight

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m, ios/sdk/WeexSDK/Sources/Component/WXSliderNeighborComponent.m
fix attribute ‘sticky’ bug while scrolling up and down quickly && and SliderNeighbor component’s guesture-blocking bug when it is used in a scrollview
=> Ios bugfix sticky and slider neighbor

html5/render/browser/extend/api/globalEvent.js
add `keepAlive=true` when calling the callback for `globalEvent.addEventListener`.
=> [html5] keep alive for global event listeners.

html5/render/browser/extend/api/stream.js, package.json
Leave `content-type` for developer to set since the content-type is not always supported by services and there's no need to deduce the content-type from the body data.
=> [html5] fix content-type error

html5/frameworks/legacy/app/bundle/bootstrap.js, html5/frameworks/legacy/app/viewport.js, html5/test/unit/default/app/bundle.js, html5/test/unit/default/app/viewport.js
> Achieve the proposal in #421 .
Ref: W3C Spec [CSS Device Adaptation](https://drafts.csswg.org/css-device-adapt/#viewport-meta)
Adding item in config script:
```html
<script type="config">
{
"viewport": {
"width": "device-width",
...
},
...
}
</script>
```
> **Maybe we will use `<meta>` tag as DSL in future.**
- `width`: number or `"device-width"` or `"device-height"`
- `height`: number or `"device-width"` or `"device-height"`
- module: `meta`
- method: `setViewport`
- args: `[viewportObject]` (just same as viewport object in config script)
=> [jsfm] Support to set viewport (achieve #421)

html5/runtime/init.js, html5/test/case/basic/css-unit.output.js, html5/test/case/basic/css-unit.source.js, html5/test/case/prepare.js, html5/test/case/tester.js, html5/test/unit/default/runtime.js, package.json
Support more CSS units without native update.
Three updates together:
1. `css-units` branch in `weexteam/weex-styler`
2. `weex-next` branch in `weexteam/weex-vue-loader`
3. `jsfm-feature-css-units` in `jinjiang/weex`
How it works: CSS value `100rem` in `<style>` will be transformed into `"100rem"` by `weex-styler` and then `100 * CSS_UNIT.REM` by `weex-vue-loader`. At the same time define global variable `CSS_UNIT` in JS Framework. So it works.
=> [jsfm] supported CSS units by global.CSS_UNIT

ios/playground/WeexDemo.xcodeproj/project.pbxproj, ios/sdk/WeexSDK.xcodeproj/project.pbxproj, ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m, ios/sdk/WeexSDK/Sources/Loader/WXWebSocketLoader.h, ios/sdk/WeexSDK/Sources/Loader/WXWebSocketLoader.m, ios/sdk/WeexSDK/Sources/Module/WXWebSocketModule.h, ios/sdk/WeexSDK/Sources/Module/WXWebSocketModule.m, ios/sdk/WeexSDK/Sources/WebSocket/SRWebSocket+Weex.h, ios/sdk/WeexSDK/Sources/WebSocket/SRWebSocket+Weex.m, ios/sdk/WeexSDK/Sources/WebSocket/WXWebSocketDefaultImpl.h, ios/sdk/WeexSDK/Sources/WebSocket/WXWebSocketDefaultImpl.m, ios/sdk/WeexSDK/Sources/WebSocket/WXWebSocketHandler.h, ios/sdk/WeexSDK/Sources/WebSocket/WXWebSocketModel.h, ios/sdk/WeexSDK/Sources/WebSocket/WXWebSocketModel.m
* 名字
- websocket
* 描述
- websocket在聊天应用，小游戏中会用到，建议加上基础功能websokcet，实现后，可以用于应用的交互场景，websocket已经是大多数程序的必备功能
* 平台
- ios,android,H5
* 类型
- module
* 解决方案
- weex 提供websocket，h5 直接用原生的websocket，安卓和ios根据w3c的websocket接口实现对应的接口，需要更改jsfm，jsfm重写方法设置功能， 支持方法的赋值功能，这样jsfm赋值的函数可以监听module的api，从而实现严格按照w3c标准的api
- weex提供默认的protocol实现，用户也可以实现自己的protocol，增强websocket功能
- 对于websocket的实例，可以参考stream的实现，根据协议的名字设置（隐风建议一个instance 一个实例）
* api
- WebSocket(
string url,
string option protocol
);
- url：需要连接的URL(string)
- protocol: 协议(string)
- send(string data)
- data：发送到服务器的数据(string)
- close(int code,string reason)
- code：表示关闭连接的状态号，默认值1000(表示正常连接关闭)(int)
- reason:可选，表示关闭的原因(string)
- onerror(e)
- 当错误发生时用于监听error事件的事件监听器。会接受一个名为error的event对象(dictionary)
- data(string)：错误数据
- onmessage(e)
- …
=> + [ios] feature: follow w3c standard.  weex provide  websocket  module

ios/sdk/WeexSDK/Sources/Manager/WXRuleManager.m
iconfont fontStorage should set when  download success
复现问题方案：
第一次打开app，iconfont 现在不成功
激活网络，第二次打开iconfont，iconfont会一直不会显示
场景：ios 10 第一次请求系统网络，还没有获取系统网络权限，以后iconfont会一直加载不成功
=> * [ios] iconfont fontStorage should not set before download

android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXListComponent.java
modify list component code style
主要重构下WXListComponent.initComponentHostView里的代码，原代码是个长函数，用几个小函数代替，抽出公共变量WXRecyclerView innerRecyclerView，避免多次bounceRecyclerView.getInnerView()，同时bounceRecyclerView抽到一个protect方法里，便于业务有需求扩充功能时从BounceRecyclerView派生一个自己的子类，在子类上增加一些功能。
=> [android] modify list component code style

ios/sdk/WeexSDK/Sources/View/WXView.m
* [ios] bugfix view event ignore when set userInteractionEnabled no
=> iOS feature 20170118

html5/render/browser/bridge/receiver.js, html5/render/browser/render/index.js
support two synchronous calls for bridge communication:
* `callNativeComponent`
* `callNativeModule`
=> [html5] support sync call for callNative.

ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m
doc:https://weex-project.io/references/modules/stream.html
ok(boolean): true if status code is bewteen 200～299.
ok's type in android is boolean. so so change the ok to bool type same as android
user can use it as follow:
```javascript
if(ret.ok === true){
console.log('get:'+ret);
me.getResult = JSON.stringify(ret.data);
}else{
me.getResult = "request failed";
}
```
refer:http://stackoverflow.com/questions/3970794/objective-c-how-to-put-boolean-values-in-json-dictionary
=> * [ios] bug fix: doc declare ok is bool type. so change the ok to bool type

.travis.yml, Gemfile, Gemfile.lock, ios/sdk/WeexSDK.xcodeproj/project.pbxproj, ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h, ios/sdk/WeexSDK/Sources/Component/WXTransform.h, ios/sdk/WeexSDK/Sources/Component/WXTransform.m, ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m, ios/sdk/WeexSDK/Sources/Model/WXComponent.m, ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m, ios/sdk/WeexSDK/Sources/Utility/WXAssert.h, ios/sdk/WeexSDK/Sources/Utility/WXLength.h, ios/sdk/WeexSDK/Sources/Utility/WXLength.m, ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m, ios/sdk/WeexSDK/Sources/WeexSDK.h
* UIView animation does not support rotation animation whose degree > 180，so we use CAAnimation to hack it.
* Using UIView animation along with CAAnimation has a lot of problems when developers use rotate/scale/translate together
* We refactor all transition properties to use CAAnimation to ensure consistency
* We also separate transform string parsing with runtime parsing to ensure performance
* tested demos:
* all the demos in playground and tests 
* http://dotwe.org/weex/7d8e99a7d5dc8ee22e2437d6d8513fec
* http://dotwe.org/weex/cad4d4cd051ab3e565f3cd42bbcac73b
* http://dotwe.org/weex/8cfadb65d744fd400728097ef7da3bcc
* related issue: #1596 #2070 #2182 #2226
=> * [ios] Refactor transform and transition 

html5/services/amd/index.js
* fix compatibility problem for global api `define` and `require`
* support `define(name, ['a', 'b'], factory(a, b) { ... })`
=> [jsfm] fix compatibility problem & support deps arguments.

html5/frameworks/legacy/app/ctrl/init.js, html5/frameworks/legacy/app/ctrl/misc.js, html5/frameworks/legacy/app/instance.js, html5/frameworks/legacy/static/create.js, html5/runtime/config.js, html5/runtime/init.js, html5/runtime/task-center.js, html5/test/case/prepare.js, html5/test/case/tester.js, html5/test/unit/default/app/ctrl.js, html5/test/unit/default/app/index.js
Move callbackManager to TaskCenter.
All callbacks from module & component are managed by TaskCenter.
=> + [jsfm] add component callback support

ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
通过 `use_frameworks!` 将 WeexSDK 以动态库形式引入项目后，对 `main.js` 的读取就不 work 了，因为 `main.js` 的路径变为了 `MyApp.app/Frameworks/MyFramework.framework/main.js`。
使用 `[NSBundle bundleForClass:self]` 可以始终正确地取出包含 `main.js` 的 bundle，不管它是 main bundle 还是什么。
=> [iOS] make loading main.js file safer

ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m
修改 `<input>` 的 value 时，`updateAttributes` 方法调用了`setAutofocus`而导致 不需要的键盘隐藏。 所以做了一些修正。
=> fix unexpected keyboard hide when modify value of the <input> .

ios/sdk/WeexSDK/Sources/Component/WXLoadingComponent.m, ios/sdk/WeexSDK/Sources/Component/WXRefreshComponent.m
=> * [ios] fire loading & refresh event only once

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m, ios/sdk/WeexSDK/Sources/Component/WXSliderComponent.m, ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m, ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.m, ios/sdk/WeexSDK/Sources/Utility/WXConvert.h, ios/sdk/WeexSDK/Sources/Utility/WXConvert.m, ios/sdk/WeexSDK/Sources/Utility/WXUtility.h, ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
+ [ios] add returnKeyType for textarea and input
- 比如input，如果用户点击了搜索按钮，自动提交表单
- 能设置返回键类型，能返回数据
- ios 和安卓设置统一返回键类型
- 组件属性
- 支持input，textarea
- 属性：returnKeyType
- 回调：onReturn
- returnKeyType:返回键类型
- value:本框内容
- 类型
- defalut;go;next;search;send,done
```javascript
<template>
<div>
<div>
<text style="font-size: 40px">oninput: {{txtInput}}</text>
<text style="font-size: 40px">onchange: {{txtChange}}</text>
<text style="font-size: 40px">onreturn: {{txtreturn}}</text>
</div>
<scroller>
<wxc-panel title="input type = text" type="primary">
<textarea
type="text"
placeholder="Input Text"
class="input"
autofocus="{{autofocus}}"
value=""
returnKeyType="done"
onchange="onchange"
oninput="oninput"
onreturn = "onreturn"
></textarea>
</wxc-panel>
</scroller>
</div>
</template>
<style>
.input {
font-size: …
```
=> + [ios] add returnKeyType for textarea and input

html5/render/vue/modules/dom.js
support using `scrollToElement` to scroll in a horizontal scroller.
=> [html5] feature enable horizontal scrolltoElement.

html5/render/browser/extend/api/stream.js
Request url would take an `undefined` after it where there's no `body` option in `fetch()`.
=> remove the `undefined` after the request url

ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
真正初始化 sdk 是在initSDKEnvironment： 函数中，这个函数是public 属性的，加载这个位置感觉上更合理(init SDK Environment execute in fuction initSDKEnvironment:, this function is public function
it is reasonable to add monitor in the location of fuction initSDKEnvironment: )
=> * [ios] change initSDKEnvironment monitor location

ios/sdk/WeexSDK/Sources/Component/WXEditComponent.m, ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
- textarea 的 placeholdlabel 的更新和 padding及border 保持一致(when textview padding or border update, placeHolderLabel update too)
- update value setting
=> * [ios] fix bug: texture: when textview padding or border update, placeHolderLabel update too

ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
-[WXSDKInstance_renderWithRequest:options:data:  ]这个方法里我注意到有写 options中 bundleUrl类型的兼容方案，但是 newOptions 这个处理后没有用到，是我理解有误还是其它问题。
=> * [iOS] model WXSDKInstance update _options property

ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
* [ios] fix bug uifont lead crash in iOS system less than 8.2 and  add font fallback for   system less than 8.2
=> * [ios] fix bug uifont lead crash in iOS system less than 8.2 

ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m
- 删除代码_layer.backgroundColor = _backgroundColor.CGColor，之前加上是为了避免cell不能从更新总恢复，现在这个代码已经在WXComponent+Display.m文件中执行了 (delete the code _layer.backgroundColor = _backgroundColor.CGColor; because it execute WXComponent+Display)
- 伪类 http://dotwe.org/weex/d763a062ec89ec82469783d07c7f477f
- 更新 http://dotwe.org/weex/6b6e4b8ddb8156a2deea703c0ad64f1a
=> * [ios] fixbug when active ,the border-radius  lose efficacy

android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java, android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
Fix linear-gradient & border-radius & clipPath cannot work together if system version is 4.3 or 4.4.
Without this fix, the [border-radius of linear-gradient div](http://dotwe.org/weex/963c9ade129f86757cecdd85651cd30e) will not work.
This is mostly likely due to OpenGL ES 3.1, which provided  "Separate shader objects" is not supported until android 5.0.
=> * [android] Fix linear-gradien problem

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java, android/sdk/src/main/java/com/taobao/weex/utils/WXFileUtils.java
WXSDKInstance 调用 renderByUrl 会检查 Url 的 scheme，如果为file，会进行本地文件的加载，但是只会进行asset目前中资源文件的加载，目前改进如下：
首先会进行本地文件的判断，如果存在则用这个文件加载
其次会在assets目录中检查文件并加载
测试：
首先保证mnt/sdcard/index.js 文件存在
再用WXSDKInstance.renderByUrl("file:///mnt/sdcard/index.js",..) 可以顺利加载
=> load weex js with file scheme

html5/render/vue/utils/component.js
fix image lazyload when body's content overflowed (height's value is bigger than body).
=> [html5] fix img lazyload when body's content overflowed.

ios/sdk/WeexSDK/Sources/Bridge/WXComponentMethod.m
=> [ios] fix: only call component method when component exist

runtime/services/broadcast-channel/index.js
在同页面中不停的切换，导致内存无法释放，代码片段如下：
data(){
return {
BroadcastNotice:new BroadcastChannel('notice111111')
}
},
created() {
this.BroadcastNotice.onmessage = event => this.$emit("onNoticeMsg", event) //泄露
// this.HundsunNotice.onmessage = event => {}  //正常
},
* Demo:
=> BroadCastChannel Memory Leak

ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.mm
Fix http://dotwe.org/vue/d4a31131178b9ab11f6dd05e5792a171
`<textarea>`component has incorrect text insets upon initialization, and it doesn't become correct until the border/padding changes which will trigger an update of insets.
* Demo:
http://dotwe.org/vue/d4a31131178b9ab11f6dd05e5792a171
=> [ios] fix incorrect initial text inset of textarea

playground/ios/WeexDemo/AppDelegate.m, playground/ios/WeexDemo/WXExtModule.m
fix complie issue with xcode13 Undefined symbols ___gcov_flush
原因：
llvm delete "_gcov_flush", try replace with "__gcov_dump/__gcov_reset" , https://reviews.llvm.org/D83149
* Demo:
=> [ios]fix complie issue with xcode13 Undefined symbols ___gcov_flush

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
Fix the problem that when the list is under one piece of data, the loading label will be displayed by default in the drop-down refresh list
原因:
下拉动作结束时，触发了scrollerview的scrollViewDidEndDragging逻辑，该逻辑中没有考虑list列表不满一屏的场景，导致默认设置loading标签的hidden为NO
解决方案:
scrollViewDidEndDragging方法中增加loading标签的displayState属性判断
* Demo:
=> [ios]Fix the problem that when the list is under one piece of data, the loading label will be displayed by default in the drop-down refresh list

ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
maxlength=5, but set the default value to 12 lengths. Before the 5th character, pasting 10 characters directly will result in
As a result, the length of leftLength=17 is larger than the position of the cursor and larger than maxleng, and the extra characters need to be filtered.
* Demo:
=> [ios]fix maxlength issues

ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
Fix the problem that the date display time is incorrect after the initial value of the date is reset when the input tag type is date|time
* Demo:
=> [ios]fix date|time reset issues

ios/sdk/WeexSDK/Sources/Component/WXLoadingComponent.mm
Fix the problem that when the list is under one piece of data, the loading label will be displayed by default in the drop-down refresh list
复现条件:
list标签数据不超过一屏时，同时存在refresh和loading标签，若上拉加载列表(没有更多数据)，仅仅快速切换(100ms)loading标签的display属性由true为false，发现列表位置不会自动还原
原因:
Probably setContentOffset: has higher priority than setContentOffset:animated:
方案:
参考refresh标签的说明，针对displayState字段不同值，调整设置setContentOffset方式
* Demo:http://dotwe.org/vue/ab6efd1b38c9beaec2cae3a99e3ecf79
<template>
<list>
<refresh class="refresh" @refresh="onrefresh" @pullingdown="onpullingdown" :display="refreshing ? 'show' : 'hide'">
<text class="indicator-text">Refreshing ...</text>
<loading-indicator class="indicator"></loading-indicator>
</refresh>
<cell v-for="num in lists">
<text class="text">{{num}}</text>
</cell>
<loading …
=> [ios]Fixed the problem that the list was not automatically restored when the loading tag was pulled up under certain conditions

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.m
When eex executes the callback processing, it performs a one-step convertContainerToImmutable operation (converting the object into an object). For NSArray objects with different empty elements, it is converted to NSMutableArray and converted to multiple objects, so the front of json points to the same object.
* Demo:
=> [ios]fix convert empty array issues

ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
jsn-dom addRule  method when src   is base64 iconfont，will crashed in iOS13.4+
* Demo:
=> [ios]fix jsn-dom addRule may crashed in iOS13.4+
